import {Phones} from "./app/shared/models/phones";

export const sample_phones: Phones[] = [
  {
    id: '1',
    name: 'Samsung S21 ultra',
    price: 394,
    tags: ['Samsung','5G'],
    favourite: false,
    stars: 4.0,
    imageUrl: 'assets/s21.jpg',
    origins: ['Vietnam'],
  },
  {
    id: '2',
    name: 'Samsung S22 ultra',
    price: 930,
    tags: ['Samsung','5G','8GB RAM'],
    favourite: false,
    stars: 3.0,
    imageUrl: 'assets/s22.jpg',
    origins: ['Vietnam'],
  },
  {
    id: '3',
    name: 'Samsung Z fold2',
    price: 450,
    tags: ['Samsung','5G','12GB RAM'],
    favourite: true,
    stars: 3.0,
    imageUrl: 'assets/s21.jpg',
    origins: ['Vietnam'],
  },
  {
    id: '4',
    name: 'Samsung Galaxy Note10',
    price: 350,
    tags: ['Samsung','5G','Note'],
    favourite: false,
    stars: 3.0,
    imageUrl: 'assets/note10.jpg',
    origins: ['Vietnam'],
  },
  {
    id: '5',
    name: 'Samsung Galaxy Note20 Ultra',
    price: 430,
    tags: ['Samsung','5G','Note'],
    favourite: true,
    stars: 2.0,
    imageUrl: 'assets/note20.jpg',
    origins: ['Vietnam'],
  },
  {
    id: '6',
    name: 'Samsung Galaxy Note22 Ultra',
    price: 920,
    tags: ['Samsung','5G','Note'],
    favourite: false,
    stars: 5.0,
    imageUrl: 'assets/note22.jpg',
    origins: ['Vietnam'],
  },
]

